name: Build Universal Binary

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    strategy:
      matrix:
        architecture: [x86_64, arm64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          if [ "${{ matrix.architecture }}" == "x86_64" ]; then
            arch -x86_64 pyenv install 3.11.7
            arch -x86_64 pyenv global 3.11.7
          else
            echo no dependecies of **arm7**
          fi  

      - name: Install pyenv
        run: brew install pyenv

      - name: Install Python for ${{ matrix.architecture }}
        run: |
          if [ "${{ matrix.architecture }}" == "x86_64" ]; then
            arch -x86_64 pyenv install 3.11.7
            arch -x86_64 pyenv global 3.11.7
          else
            arch -arm64 pyenv install 3.11.7
            arch -arm64 pyenv global 3.11.7
          fi
        env:
          pythonLocation: /Users/runner/hostedtoolcache/Python/3.11.9/${{ matrix.architecture }}
          ARCHFLAGS: "-arch ${{ matrix.architecture }}"

      - name: Install dependencies
        run: |
          if [ "${{ matrix.architecture }}" == "x86_64" ]; then
            arch -x86_64 pip install pyinstaller
          else
            arch -arm64 pip install pyinstaller
          fi

      - name: Build executable for ${{ matrix.architecture }}
        run: |
          if [ "${{ matrix.architecture }}" == "x86_64" ]; then
            arch -x86_64 pyinstaller pixelator2_intel.spec
          else
            arch -arm64 pyinstaller pixelator2_arm.spec
          fi
          ls -l dist/

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: pixelator2_${{ matrix.architecture }}
          path: dist/pixelator2_${{ matrix.architecture }} 

  combine:
    runs-on: macos-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: pixelator2_x86_64
          path: dist/x86_64

      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: pixelator2_arm64
          path: dist/arm64

      - name: Combine executables using lipo
        run: |
          lipo -create -output dist/pixelator2_universal dist/x86_64/pixelator2_x86_64 dist/arm64/pixelator2_arm64

      - name: Upload universal binary
        uses: actions/upload-artifact@v3
        with:
          name: pixelator2_universal
          path: dist/pixelator2_universal