name: Build Universal Binary

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    strategy:
      matrix:
        architecture: [x86_64, arm64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install pyenv
        run: brew install pyenv

      - name: Install Python for ${{ matrix.architecture }}
        run: |
          pyenv install 3.11.7
          pyenv global 3.11.7

      - name: Install dependencies
        run: |
          pip install pyinstaller

      - name: Build executable for ${{ matrix.architecture }}
        run: |
          if [ "${{ matrix.architecture }}" == "x86_64" ]; then
            pyinstaller pixelator2_intel.spec
          else
            pyinstaller pixelator2_arm.spec
          fi

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: pixelator2_${{ matrix.architecture }}
          path: dist/pixelator2_${{ matrix.architecture }} 
                  
  combine:
    runs-on: macos-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: pixelator2_x86_64
          path: dist/x86_64

      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: pixelator2_arm64
          path: dist/arm64

      - name: Combine executables using lipo
        run: |
          lipo -create -output dist/pixelator2_universal dist/x86_64/pixelator2_intel dist/arm64/pixelator2_arm

      - name: Upload universal binary
        uses: actions/upload-artifact@v3
        with:
          name: pixelator2_universal
          path: dist/pixelator2_universal